server:
  listenaddr: ""
  port: 6868
  responseheaders:
    Access-Control-Allow-Credentials: "true"
    Access-Control-Allow-Headers: content-type
    Access-Control-Allow-Methods: GET,HEAD,PUT,PATCH,POST,DELETE
    Access-Control-Allow-Origin: '*'
    Access-Control-Expose-Headers: X-Total-Count
database:
  dbname: attackSeaman
  connection: mongodb://attackSeaman:cuccs1sgreat@127.0.0.1:27017
  tbname: enterprise
